export const HANDLE_DIGITS = "HANDLE_DIGITS";
export const HANDLE_PLUS = "HANDLE_PLUS";
export const HANDLE_MINUS = "HANDLE_MINUS";
export const HANDLE_MULTIPLICATION = "HANDLE_MULTIPLICATION";
export const HANDLE_DIVISION = "HANDLE_DIVISION";
export const HANDLE_EQUAL = "HANDLE_EQUAL";
